export enum SportCategory {
 'Fútbol'                 = 'Fútbol',
 'Futbol'                 = 'Futbol',  
 'Baloncesto'             = 'Baloncesto',
 'Tenis'                  = 'Tenis',
 'Formula1'               = 'Formula1',
 'F1'                     = 'F1',
 'Boxeo'                  = 'Boxeo',
 'Rally'                  = 'Rally',
 'Moto GP'                = 'Moto GP',
 'Golf'                   = 'Golf',
 'Béisbol'                = 'Béisbol',
 'Beisbol'                = 'Beisbol',
 'Cricket'                = 'Cricket',
 'Artes Marciales Mixtas' = 'Artes Marciales Mixtas',
 'MMA'                    = 'MMA',
 'Hockey'                 = 'Hockey',
 'Ciclismo'               = 'Ciclismo',
}
